logo: /assets/css/headshotnew.png
title: Cyrus Baruc | Data Analytics & BI Portfolio
description: Power BI/Power Platform Developer
show_downloads: false
theme: jekyll-theme-minimal
include:
  - assets/css/styles.css
